[package]
name = "umberwm"
version = "0.0.23"
authors = ["yazgoo <yazgoo@gmail.com>"]
edition = "2018"
license = "MIT"
description = "minimalist X11 window manager"
readme = "README.md"
homepage = "https://github.com/yazgoo/umberwm"
repository = "https://github.com/yazgoo/umberwm"
keywords = ["wm", "x11", "terminal"]
categories = ["GUI"]

[dependencies]
regex = "1.3"
miniserde = "0.1"
thiserror = "1.0.24"
[dependencies.xcb]
version = "0.9"
features = ["randr"]
