#!/bin/bash

# Custom actions go here

mkdir -p "$HOME"/.local/share/umberwm

while true; do
  umberwm &>> "$HOME"/.local/share/umberwm/umberwm.log
  # If umberwm returns exit code 123, restart, otherwise quit.
  [ $? -ne 123 ] && break
done
